name: Fly Deploy
on:
  pull_request:
    types: 
      - closed
    
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
